### ISSUE TITLE
How use cordonbleu ?

### ISSUE THREAD

**Issue by nicodeur** [BenRomberg/cordonbleu#1]
Hello,

I would like test cordonbleu to do codereview on my campany.

I just install it, and localhost:8080 works!

But how create user to use cordonbleu ? I have no user on mongobd (db.user.find() empty).

I add 2 repository on my repos folder, and i can't view it!

Can you help me ?

**Comment by nicodeur** [comment]
You have to put your email adress and your password to register as admin on cordonbleu.

To add a repositoy, you have to do it after registration and after create a team.

**Comment by BenRomberg** [comment]
Thanks @nicodeur for pointing this out! I added the missing installation notes to the README.md.
