### ISSUE TITLE
Question : How does commit import work ?

### ISSUE THREAD

**Issue by nicodeur** [BenRomberg/cordonbleu#3]
Hello,

I import 1 existing repository, but I don't see old commits.

There is a task who import old commit into database ?

For the moment, pull doesn't work because of proxy problem, but my repo was cloned succesffuly, on repos folder, so I think I should see commits!

I have any commit from me on this project, no impact ?

![image](https://cloud.githubusercontent.com/assets/6707556/22967627/84572520-f367-11e6-869b-4494871ebe8f.png)

**Comment by BenRomberg** [comment]
Hey @nicodeur, yes it should work. There's a background task pulling form the remote repositories every minute. Any new commits will be imported into the database.

Not sure what's going wrong with this repository, maybe there's a hint in the logs? Take a look in the database to see which commits have been imported. Also, note that you've selected the `ndeblock` user, so only commits from that user are shown.

**Comment by nicodeur** [comment]
Ok, I resolve it. Infact, I tried to import a svn project with git svn clone and i did'nt make the good thing.

Now it's work! Commit are import during the cordonbleu pulling, So create a new repo with git clone on repos folder can't work!

I will create a new issue to explain how import an svn repository, thanks for your help and your reactivity.
