### ISSUE TITLE
How many time to develop new Feature (code explorer - notification) ?

### ISSUE THREAD

**Issue by nicodeur** [BenRomberg/cordonbleu#4]
Hello,

I would like add a code explorer like on gitlab. It's to make code review on one class in particular (I would like make code review on old project).

Difficult with existant code ? How many time do you think to develop it ?

I think another thing miss, when I add a new comment, I have no possibility to notify I corrected the problem, or to reject comment. Indeed, I see comment as a tasklist to improve my project, and I would like follow it. Perhaps miss a dashboard to resume task to make ?

Another idea : add a research by commit message

What do you think about it ?

I expose my idea, and I can help you to develop it. I think cordonbleu is a good begining (I didn't find my happyness with other tool - gerrit,codebrag etc...)

**Comment by BenRomberg** [comment]
We're using cordonbleu at work every day and are pretty happy with today's features. Feel free to dig into the code to implement more features.

Btw, you can notify other users in comments by typing `@username` (with auto-completion) if that helps.
